# Generated by Django 5.2.3 on 2025-06-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Booking ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('no_of_guests', models.IntegerField(verbose_name='Number of Guests')),
                ('booking_date', models.DateField(verbose_name='Booking Date')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Menu Item ID')),
                ('title', models.CharField(max_length=255, verbose_name='Menu Item Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
